apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: default
spec:
  type: ExternalName
  externalName: 127.0.0.1
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  username: cm9vdAo=
  password: cm9vdAo=
