spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      platform: mysql
      encoding: UTF-8
      schema-locations: classpath:/db/mysql/balance_db.sql

mybatis:
  type-aliases-package: com.pkg.balance.mgmt.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info
    com.pkg.balance.mgmt: debug
    org.springframework.web: DEBUG

server:
  servlet:
    context-path: /

redisson:
  address: ${SPRINT_REDIS_URL}
  password: ${SPRINT_REDIS_PASSWORD}
  username: ${SPRINT_REDIS_USERNAME}
  database: 0
  timeout: 3000
  connectionPoolSize: 64
  connectionMinimumIdleSize: 10
