spring:
  datasource:
    url: jdbc:mysql://localhost:3306/balance_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      platform: mysql
      encoding: UTF-8
      schema-locations: classpath:/db/mysql/balance_db.sql

mybatis:
  type-aliases-package: com.pkg.balance.mgmt.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info
    com.pkg.balance.mgmt: debug
    org.springframework.web: DEBUG

server:
  port: 8080
  servlet:
    context-path: /

redisson:
  address: "redis://127.0.0.1:6379"
  password: "myuser_password"
  username: "myuser"
  database: 0
  timeout: 3000
  connectionPoolSize: 64
  connectionMinimumIdleSize: 10

rocketmq:
  namesrv:
    addr: localhost:9876
  producer:
    group: TransactionProducerGroup
  consumer:
    group: TransactionConsumerGroup

management:
  health:
    redis:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

