   apiVersion: v1
   kind: Service
   metadata:
     name: balance-mgmt-api
     namespace: default
   spec:
     type: LoadBalancer
     selector:
       app: balance-mgmt-api
     ports:
       - protocol: TCP
         port: 8080
         targetPort: 8080
   