   apiVersion: v1
   kind: Service
   metadata:
     name: balance-mgmt-api
     namespace: default
   spec:
     type: NodePort
     selector:
       app: balance-mgmt-api
     ports:
       - protocol: TCP
         port: 8080
         targetPort: 8080
         nodePort: 30000  # 可以选择一个 30000-32767 之间的端口
   