   apiVersion: v1
   kind: Service
   metadata:
     name: redis-service
     namespace: default
   spec:
     type: ExternalName
     externalName: localhost
     ports:
     - port: 6379
       targetPort: 6379
